# Generated by Django 3.2.13 on 2022-06-07 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MenuHum', '0004_remove_menu_hum_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu_hum',
            old_name='active',
            new_name='is_active',
        ),
    ]
