# Generated by Django 3.2.13 on 2022-06-07 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MenuHum', '0006_menu_hum_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu_hum',
            name='imagen',
        ),
    ]
