# Generated by Django 3.2.13 on 2022-06-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MenuHum', '0007_remove_menu_hum_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_hum',
            name='imagen',
            field=models.ImageField(null=True, upload_to='producto'),
        ),
    ]
