# Generated by Django 3.2.13 on 2022-06-07 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MenuHum', '0008_menu_hum_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu_hum',
            name='imagen',
        ),
    ]
