# Generated by Django 3.2.13 on 2022-06-25 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MenuHum', '0009_remove_menu_hum_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_hum',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
    ]
