# Generated by Django 3.2.13 on 2022-06-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido', models.CharField(max_length=40)),
                ('telefono', models.IntegerField()),
                ('email', models.CharField(max_length=40)),
                ('nombre_mascota', models.CharField(max_length=15)),
                ('raza', models.CharField(max_length=15)),
                ('edad', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
