# Generated by Django 3.2.13 on 2022-06-07 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MenuPet', '0002_menu_pet_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu_pet',
            old_name='active',
            new_name='is_active',
        ),
    ]
